describe('Method Syntax', () => {
  describe('8.1', () => {
    describe(`A DID method specification MUST define exactly 
      one method-specific DID scheme that is identified by exactly 
      one method name as specified by the method-name rule in §3.1 DID Syntax.`, () => {
      test.todo('untestable');
    });
    describe(`The DID method specification MUST specify how to 
      generate the method-specific-id component of a DID.`, () => {
      test.todo('untestable');
    });
    describe(`The DID method specification MUST define sensitivity 
      and normalization of the value of the method-specific-id.`, () => {
      test.todo('untestable');
    });
    describe(`The method-specific-id value MUST be unique within a DID method. 
      The method-specific-id value itself might be globally unique.`, () => {
      test.todo('untestable');
    });
    describe(`Any DID generated by a DID method MUST be globally unique.`, () => {
      test.todo('untestable');
    });
    describe(`To reduce the chances of method-name conflicts, 
      a DID method specification SHOULD be registered in 
      the DID Specification Registries [DID-SPEC-REGISTRIES].`, () => {
      test.todo('untestable');
    });
    describe(`The method-specific-id format MAY include colons. 
      The use of colons MUST comply syntactically with the method-specific-id ABNF rule.`, () => {
      test.todo('untestable');
    });
  });
});
